package com.example.ui

object LanguageHelper {
    fun getText(isMarathi: Boolean, key: String): String {
        val map = if (isMarathi) marathiMap else englishMap
        return map[key] ?: key
    }

    private val marathiMap = mapOf(
        "app_title" to "कामचा हिशोब",
        "app_subtitle" to "तुमचा दैनंदिन कामाचा व पैशांचा हिशोब",
        "add_record" to "नवीन नोंद जोडा",
        "edit_record" to "नोंद दुरुस्त करा",
        "delete_record" to "नोंद हटवा",
        "delete_confirm" to "तुम्हाला ही नोंद नक्की हटवायची आहे का?",
        "total_earnings" to "एकूण कमाई",
        "paid_amount" to "जमा रक्कम",
        "pending_amount" to "शिल्लक बाकी",
        "total_records" to "एकूण नोंदी",
        "filter_client" to "ग्राहक निवडा",
        "filter_status" to "पैसे मिळाल्याची स्थिती",
        "all" to "सर्व",
        "paid" to "पैसे मिळाले (Paid)",
        "pending" to "पैसे बाकी (Pending)",
        "work_title" to "दैनंदिन काम / कार्य (Daily Task)",
        "client_name" to "प्रकल्प / ग्राहकाचे नाव (Project / Client Name)",
        "work_type" to "कामाचा प्रकार (Work Type)",
        "hourly" to "ताशी (Hourly)",
        "daily" to "रोजंदारी (Daily)",
        "fixed" to "ठराविक / कॉन्ट्रॅक्ट (Fixed)",
        "rate" to "दर (Rate per hour/day) [रु.]",
        "quantity_hours" to "घालवलेला वेळ / कालावधी (Time Spent)",
        "work_date" to "कामाची तारीख (Work Date) [YYYY-MM-DD]",
        "notes" to "इतर माहिती / नोट्स (Notes) [पर्यायी]",
        "save" to "जतन करा (Save)",
        "cancel" to "रद्द करा (Cancel)",
        "no_records" to "अद्याप कोणतीही नोंद केलेली नाही. सुरू करण्यासाठी खालील '+' बटण दाबा!",
        "ai_updates_title" to "AI हिशोब अहवाल व अपडेट्स",
        "ai_updates_desc" to "तुमच्या सर्व कामाचा अहवाल तयार करा आणि थेट मालकाला किंवा ग्राहकाला WhatsApp वर पाठवा!",
        "generate_report" to "AI द्वारे अहवाल तयार करा",
        "generating" to "अहवाल तयार होत आहे...",
        "whatsapp_share" to "WhatsApp वर शेअर करा",
        "direct_share" to "थेट शेअर करा",
        "view_records" to "नोंदी",
        "ai_reports" to "AI अपडेट्स",
        "m_text_field_empty" to "कृपया आवश्यक माहिती भरा",
        "rate_error" to "कृपया वैध दर टाका",
        "qty_error" to "कृपया वैध संख्या टाका",
        "today" to "आज",
        "yesterday" to "काल",
        "client_suggestions" to "आधीचे ग्राहक:",
        "status_updated" to "स्थिती बदलली",
        "toggle_language" to "English",
        "active_filters" to "सक्रिय फिल्टर्स",
        "clear_filters" to "फिल्टर्स काढा",
        "upi_setup_title" to "UPI पेमेंट सेटअप",
        "upi_id_label" to "UPI आयडी (उदा. 9876543210@paytm)",
        "payee_name_label" to "खातेदाराचे नाव (बँकेत असलेले)",
        "upi_enabled_label" to "UPI द्वारे थेट पेमेंट पर्याय सुरू करा",
        "upi_qr_title" to "UPI द्वारे पैसे भरण्यासाठी स्कॅन करा",
        "upi_qr_subtitle" to "GPay, PhonePe, Paytm किंवा कोणत्याही UPI ॲपद्वारे स्कॅन करा",
        "upi_share_request" to "पेमेंट लिंक शेअर करा",
        "upi_vpa_invalid" to "कृपया वैध UPI आयडी प्रविष्ट करा",
        "upi_name_invalid" to "कृपया खातेदाराचे नाव प्रविष्ट करा",
        "upi_settings_saved" to "UPI माहिती यशस्वीरित्या जतन केली!",
        "pay_via_upi" to "UPI द्वारे पैसे घ्या",
        "share_payment_link" to "UPI पेमेंट लिंक शेअर करा",
        "total_pending_upi" to "शिल्लक कामाचे पैसे",
        "upi_settings_btn" to "UPI सेटिंग्ज"
    )

    private val englishMap = mapOf(
        "app_title" to "Kamacha Hisob",
        "app_subtitle" to "Your Daily Work & Payment Tracker",
        "add_record" to "Add New Record",
        "edit_record" to "Edit Work Record",
        "delete_record" to "Delete Record",
        "delete_confirm" to "Are you sure you want to delete this record?",
        "total_earnings" to "Total Earnings",
        "paid_amount" to "Total Paid",
        "pending_amount" to "Pending Balance",
        "total_records" to "Total Records",
        "filter_client" to "Select Client",
        "filter_status" to "Payment Status",
        "all" to "All",
        "paid" to "Paid",
        "pending" to "Pending",
        "work_title" to "Daily Task / Work Done",
        "client_name" to "Project / Client Name",
        "work_type" to "Work Type",
        "hourly" to "Hourly",
        "daily" to "Daily",
        "fixed" to "Fixed / Contract",
        "rate" to "Rate (₹)",
        "quantity_hours" to "Time Spent / Duration",
        "work_date" to "Work Date (YYYY-MM-DD)",
        "notes" to "Additional Notes (Optional)",
        "save" to "Save Record",
        "cancel" to "Cancel",
        "no_records" to "No records entered yet. Press the '+' button below to start!",
        "ai_updates_title" to "AI Billing Reports & Updates",
        "ai_updates_desc" to "Generate automatic professional summaries of your work and send them directly to clients on WhatsApp!",
        "generate_report" to "Generate AI Report",
        "generating" to "Generating report...",
        "whatsapp_share" to "Share on WhatsApp",
        "direct_share" to "Share Directly",
        "view_records" to "Work Records",
        "ai_reports" to "AI Updates",
        "m_text_field_empty" to "Please fill in this required field",
        "rate_error" to "Please enter a valid rate",
        "qty_error" to "Please enter a valid quantity",
        "today" to "Today",
        "yesterday" to "Yesterday",
        "client_suggestions" to "Previous Clients:",
        "status_updated" to "Status Updated",
        "toggle_language" to "मराठी",
        "active_filters" to "Active Filters",
        "clear_filters" to "Clear Filters",
        "upi_setup_title" to "UPI Payment Setup",
        "upi_id_label" to "UPI ID / VPA (e.g. 9876543210@paytm)",
        "payee_name_label" to "Payee Name (As in bank account)",
        "upi_enabled_label" to "Enable direct payment requests via UPI",
        "upi_qr_title" to "Scan to Pay via UPI",
        "upi_qr_subtitle" to "Scan using GPay, PhonePe, Paytm or any UPI App",
        "upi_share_request" to "Share Payment Link",
        "upi_vpa_invalid" to "Please enter a valid UPI ID",
        "upi_name_invalid" to "Please enter payee name",
        "upi_settings_saved" to "UPI Settings saved successfully!",
        "pay_via_upi" to "Collect via UPI",
        "share_payment_link" to "Share UPI Link",
        "total_pending_upi" to "Outstanding Balance Payment",
        "upi_settings_btn" to "UPI Settings"
    )
}
